version: '3'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret_mongodb_password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./data:/data/
    ports:
      - 27017-27019:27017-27019
    expose:
      - '27017-27019'